"""empty message

Revision ID: 42c830791662
Revises: 
Create Date: 2019-10-31 09:51:00.866650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c830791662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('census_learn_sql', 'major industry_code')
    op.drop_column('census_learn_sql', 'house-with-family')
    op.drop_column('census_learn_sql', 'member_of_labor')
    op.drop_column('census_learn_sql', 'reason_for_unemployment')
    op.drop_column('census_learn_sql', 'veteran benefits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('census_learn_sql', sa.Column('veteran benefits', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('census_learn_sql', sa.Column('reason_for_unemployment', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('census_learn_sql', sa.Column('member_of_labor', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('census_learn_sql', sa.Column('house-with-family', sa.VARCHAR(length=1000), nullable=True))
    op.add_column('census_learn_sql', sa.Column('major industry_code', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
